# Generated by Django 6.0.3 on 2026-03-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_memberprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='admin_code',
            field=models.CharField(blank=True, help_text='Admin registration code', max_length=50),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='is_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='user_type',
            field=models.CharField(choices=[('member', 'Regular Member'), ('admin_request', 'Admin Request (Pending)'), ('admin', 'Church Administrator')], default='member', max_length=20),
        ),
    ]
